version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    restart: always
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: [ "/fastapi_app/docker/celery.sh", "celery" ]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

volumes:
  postgres_data: